// ignore_for_file: constant_identifier_names

const URL_BASE =
    "http://profissionaisexternos.sauderesidence.tk/SaudeResidenceHomeCareServices/srhcws/";

const BANCODB = "srmobile.db";

const TB_FICHAENFERMAGEM = "TB_FICHAENFERMAGEM";
const TB_FICHAENFERMAGEM_ID = "ID";
const TB_FICHAENFERMAGEM_IDADMISSION = "IDADMISSION";
const TB_FICHAENFERMAGEM_IDCAPCONSULT = "IDCAPCONSULT";
const TB_FICHAENFERMAGEM_IDPROFAGENDA = "IDPROFAGENDA";
const TB_FICHAENFERMAGEM_DATAINICIO = "DATAINICIO";
const TB_FICHAENFERMAGEM_DATAFIM = "DATAFIM";
const TB_FICHAENFERMAGEM_IDPROFESSIONAL = "IDPROFESSIONAL";
const TB_FICHAENFERMAGEM_ACOMPANHANTE = "ACOMPANHANTE";
const TB_FICHAENFERMAGEM_HOSPITAL = "HOSPITAL";
const TB_FICHAENFERMAGEM_CUIDADOBANHO = "CUIDADOBANHO";
const TB_FICHAENFERMAGEM_CUIDADOVESTIR = "CUIDADOVESTIR";
const TB_FICHAENFERMAGEM_CUIDADOTRANSFERENCIA = "CUIDADOTRANSFERENCIA";
const TB_FICHAENFERMAGEM_CUIDADOCONTINENCIA = "CUIDADOCONTINENCIA";
const TB_FICHAENFERMAGEM_CUIDADOALIMENTACAO = "CUIDADOALIMENTACAO";
const TB_FICHAENFERMAGEM_UTILIZACAOTQT = "UTILIZACAOTQT";
const TB_FICHAENFERMAGEM_UTILIZACAOCNE = "UTILIZACAOCNE";
const TB_FICHAENFERMAGEM_UTILIZACAOGT = "UTILIZACAOGT";
const TB_FICHAENFERMAGEM_UTILIZACAOCVD = "UTILIZACAOCVD";
const TB_FICHAENFERMAGEM_UTILIZACAOOUTROS = "UTILIZACAOOUTROS";
const TB_FICHAENFERMAGEM_UTILIZACAOOUTROSTEXTO = "UTILIZACAOOUTROSTEXTO";
const TB_FICHAENFERMAGEM_OXIGENOTERAPIACILINDRO = "OXIGENOTERAPIACILINDRO";
const TB_FICHAENFERMAGEM_OXIGENOTERAPIACONCENTRADOR =
    "OXIGENOTERAPIACONCENTRADOR";
const TB_FICHAENFERMAGEM_OXIGENOTERAPIACONTINUO = "OXIGENOTERAPIACONTINUO";
const TB_FICHAENFERMAGEM_OXIGENOTERAPIANAO = "OXIGENOTERAPIANAO";
const TB_FICHAENFERMAGEM_VENTILACAOMECANICA = "VENTILACAOMECANICA";
const TB_FICHAENFERMAGEM_VENTILACAOMECANICAEQUIPAMENTO =
    "VENTILACAOMECANICAEQUIPAMENTO";
const TB_FICHAENFERMAGEM_PAMAX = "PAMAX";
const TB_FICHAENFERMAGEM_PAMIN = "PAMIN";
const TB_FICHAENFERMAGEM_FERIDAPRESSAO = "FERIDAPRESSAO";
const TB_FICHAENFERMAGEM_FERIDAVASCULOGENCIA = "FERIDAVASCULOGENCIA";
const TB_FICHAENFERMAGEM_FERIDACIRURGIA = "FERIDACIRURGIA";
const TB_FICHAENFERMAGEM_FERIDAOUTROS = "FERIDAOUTROS";
const TB_FICHAENFERMAGEM_DIAG001 = "DIAG001";
const TB_FICHAENFERMAGEM_DIAG002 = "DIAG002";
const TB_FICHAENFERMAGEM_DIAG003 = "DIAG003";
const TB_FICHAENFERMAGEM_DIAG004 = "DIAG004";
const TB_FICHAENFERMAGEM_DIAG005 = "DIAG005";
const TB_FICHAENFERMAGEM_DIAG006 = "DIAG006";
const TB_FICHAENFERMAGEM_DIAG007 = "DIAG007";
const TB_FICHAENFERMAGEM_DIAG008 = "DIAG008";
const TB_FICHAENFERMAGEM_DIAG009 = "DIAG009";
const TB_FICHAENFERMAGEM_DIAG010 = "DIAG010";
const TB_FICHAENFERMAGEM_DIAG011 = "DIAG011";
const TB_FICHAENFERMAGEM_DIAG012 = "DIAG012";
const TB_FICHAENFERMAGEM_DIAG013 = "DIAG013";
const TB_FICHAENFERMAGEM_DIAG014 = "DIAG014";
const TB_FICHAENFERMAGEM_DIAG015 = "DIAG015";
const TB_FICHAENFERMAGEM_PROC001 = "PROC001";
const TB_FICHAENFERMAGEM_PROC002 = "PROC002";
const TB_FICHAENFERMAGEM_PROC003 = "PROC003";
const TB_FICHAENFERMAGEM_PROC004 = "PROC004";
const TB_FICHAENFERMAGEM_PROC005 = "PROC005";
const TB_FICHAENFERMAGEM_PROC006 = "PROC006";
const TB_FICHAENFERMAGEM_PROC007 = "PROC007";
const TB_FICHAENFERMAGEM_PROC008 = "PROC008";
const TB_FICHAENFERMAGEM_PROCOUTROS = "PROCOUTROS";
const TB_FICHAENFERMAGEM_PROCOUTROSTEXTO = "PROCOUTROSTEXTO";
const TB_FICHAENFERMAGEM_CUID001 = "CUID001";
const TB_FICHAENFERMAGEM_CUID002 = "CUID002";
const TB_FICHAENFERMAGEM_CUID003 = "CUID003";
const TB_FICHAENFERMAGEM_CUID004 = "CUID004";
const TB_FICHAENFERMAGEM_CUID005 = "CUID005";
const TB_FICHAENFERMAGEM_CUID006 = "CUID006";
const TB_FICHAENFERMAGEM_CUID007 = "CUID007";
const TB_FICHAENFERMAGEM_CUID008 = "CUID008";
const TB_FICHAENFERMAGEM_CUIDOUTROS = "CUIDOUTROS";
const TB_FICHAENFERMAGEM_CUIDOUTROSTEXTO = "CUIDOUTROSTEXTO";
const TB_FICHAENFERMAGEM_BRADENPERCEPCAOSENSORIAL = "BRADENPERCEPCAOSENSORIAL";
const TB_FICHAENFERMAGEM_BRADENUMIDADE = "BRADENUMIDADE";
const TB_FICHAENFERMAGEM_BRADENATIVIDADE = "BRADENATIVIDADE";
const TB_FICHAENFERMAGEM_BRADENMOBILIDADE = "BRADENMOBILIDADE";
const TB_FICHAENFERMAGEM_BRADENNUTRICAO = "BRADENNUTRICAO";
const TB_FICHAENFERMAGEM_BRADENFICCAO = "BRADENFICCAO";
const TB_FICHAENFERMAGEM_OBSERVACAO = "OBSERVACAO";
const TB_FICHAENFERMAGEM_ASSINATURAPACIENTE = "ASSINATURAPACIENTE";
const TB_FICHAENFERMAGEM_ASSINATURAPROFISSIONAL = "ASSINATURAPROFISSIONAL";
const TB_FICHAENFERMAGEM_LATITUDE = "LATITUDE";
const TB_FICHAENFERMAGEM_LONGITUDE = "LONGITUDE";
const TB_FICHAENFERMAGEM_NMPACIENTE = "NMPACIENTE";

const URL_ESQUECEU_SENHA = "${URL_BASE}esqueceusenha/";
const URL_VALIDAR_LOGIN_SENHA = "${URL_BASE}validarloginsenha/";
const URL_ALTERAR_SENHA = "${URL_BASE}alterarsenha/";
const URL_LISTAR_AGENDA = "${URL_BASE}listaragendaporprofissional/";
const URL_ADICIONAR_FICHA_TERAPIA = "${URL_BASE}addfichaterapia/";
const URL_ADICIONAR_FICHA_MEDICA = "${URL_BASE}addfichamedica/";
const URL_ADICIONAR_FICHA_ENFERMAGEM = "${URL_BASE}addfichaenfermagem/";

const URL_RETORNAR_PLANO_TERAPEUTICO = "${URL_BASE}retornarplanoterapeutico/";

const LBL_FICHAENF_DIAGNOSTICO_001 = "Risco para aspiração";
const LBL_FICHAENF_DIAGNOSTICO_002 = "Nutrição alterada";
const LBL_FICHAENF_DIAGNOSTICO_003 = "Memória Prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_004 = "Incontinência Urinária";
const LBL_FICHAENF_DIAGNOSTICO_005 = "Risco de Quedas";
const LBL_FICHAENF_DIAGNOSTICO_006 =
    "Risco para integridade da pele prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_007 = "Controle ineficaz do regime terapêutico";
const LBL_FICHAENF_DIAGNOSTICO_008 = "Deglutição prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_009 = "Padrão de sono perturbado";
const LBL_FICHAENF_DIAGNOSTICO_010 = "Interação social prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_011 = "Risco de constipação";
const LBL_FICHAENF_DIAGNOSTICO_012 = "Comunicação verbal prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_013 = "Mobilidade física prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_014 = "Eliminação urinária prejudicada";
const LBL_FICHAENF_DIAGNOSTICO_015 = "Risco para infecção";

const LBL_FICHAENF_PROCEDIMENTO_001 =
    "Colocação e/ou troca de cateter vesical de demora";
const LBL_FICHAENF_PROCEDIMENTO_002 =
    "Colocação e/ou troca de cateter nasoenteral";
const LBL_FICHAENF_PROCEDIMENTO_003 =
    "Colocação e/ou troca de cateter nasogástrico";
const LBL_FICHAENF_PROCEDIMENTO_004 = "Troca de traqueóstomo";
const LBL_FICHAENF_PROCEDIMENTO_005 = "Cateterismo vesical de alívio";
const LBL_FICHAENF_PROCEDIMENTO_006 = "Troca de cistostomia";
const LBL_FICHAENF_PROCEDIMENTO_007 = "Troca de cateter de gastrostomia";
const LBL_FICHAENF_PROCEDIMENTO_008 = "Outros procedimentos";
const LBL_FICHAENF_PLANOCUIDADO_001 =
    "Elevar a cabeceira a 45 graus, no mínimo, para administrar a dieta ou ofertar a alimentação por via oral.";
const LBL_FICHAENF_PLANOCUIDADO_002 =
    "Para a dieta enteral, se houver necessidade de aspiração de vias aéreas durante a aspiração.";
const LBL_FICHAENF_PLANOCUIDADO_003 =
    "Realizar higiene íntima, com troca de fraldas (se necessário), após urinar ou evacuar.";
const LBL_FICHAENF_PLANOCUIDADO_004 =
    "Realizar mudanças de decúbito(de posição) a cada 02 e 03 horas.";
const LBL_FICHAENF_PLANOCUIDADO_005 =
    "Fazer uso de almofadas, travesseiros, rolos de apoiar e dar conforto ao paciente.";
const LBL_FICHAENF_PLANOCUIDADO_006 =
    "Fazer uso do AGE(óleo com ácidos graxos essenciais) nos locais com maior predisposição para o desenvolvimento de úlceras, como região sacra, maleolar, trocantórica e calcânea.";
const LBL_FICHAENF_PLANOCUIDADO_007 =
    "Lavar cateter nasoenteral, nasogástrico ou de gastrostomia, SEMPRE, antes e após admnistração de dieta ou medicação";
const LBL_FICHAENF_PLANOCUIDADO_008 =
    "Antes de administrar medicação em comprimidos por cateteres (nasoenteral ou nasogástrico), macerar, colocar de molho e administrar a medicação.";

const List<String> LISTA_FICHATERAPIA_PARTICIPACAO = [
  'SELECIONE',
  'ATIVO',
  'ATIVO ASSISTIDO',
  'PASSIVO',
  'NÃO REALIZADO'
];

const List<String> LISTA_FICHATERAPIA_EXECUCAO = [
  'SELECIONE',
  'COMPLETA',
  'PARCIAL',
  'MÍNIMA',
  'NÃO REALIZADO'
];
