import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';

class CriaBanco {
  // Construtor com acesso privado
  CriaBanco._();

  // Criar uma instancia de CriaBanco
  static final CriaBanco instance = CriaBanco._();

  // Instancia do SQLite
  static Database? _database;

  get database async {
    if (_database != null) {
      return _database;
    } else {
      return await _initDatabase();
    }
  }

  _initDatabase() async {
    return await openDatabase(join(await getDatabasesPath(), "srmobile.db"),
        version: 1, onCreate: _onCreate);
  }

  _onCreate(db, versao) async {
    await db.execute(_sqlFichaTerapia);
    await db.execute(_sqlFichaMedica);
  }

  String get _sqlFichaTerapia => '''
  CREATE TABLE TB_FICHATERAPIA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    IDADMISSION INTEGER, 
    IDCAPCONSULT INTEGER, 
    IDPROFAGENDA INTEGER, 
    DATAINICIO TEXT, 
    DATAFIM TEXT, 
    PARTICIPACAOCLIENTE TEXT, 
    EXECUCAOTECNICAPROPOSTA TEXT, 
    OBSERVACAO TEXT, 
    ASSINATURAPACIENTE TEXT, 
    ASSINATURAPROFISSIONAL TEXT, 
    LATITUDE TEXT, 
    LONGITUDE TEXT, 
    IDPROFESSIONAL INTEGER, 
    NMPACIENTE TEXT
  );
  ''';

  String get _sqlFichaMedica => '''
  CREATE TABLE TB_FICHAMEDICA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IDADMISSION INTEGER NOT NULL, 
    IDCAPCONSULT INTEGER NOT NULL,
    IDPROFAGENDA INTEGER NOT NULL, 
    DATAINICIO TEXT NOT NULL, 
    DATAFIM TEXT NOT NULL, 
    IDPROFESSIONAL INTEGER NOT NULL, 
    HD TEXT NOT NULL, 
    ACOMPANHANTE TEXT NOT NULL, 
    SITUACAOCLINICA TEXT NOT NULL, 
    JUSTIFICATIVAATENDIMENTODOMICILIAR TEXT, 
    FISIOTERAPIAMOTORA INTEGER NOT NULL,
    FISIOTERAPIARESPIRATORIA INTEGER NOT NULL, 
    NUTRICIONISTA INTEGER NOT NULL, 
    FONOTERAPIA INTEGER NOT NULL, 
    ENFERMAGEM INTEGER NOT NULL, 
    TERAPIAOCUPACIONAL INTEGER NOT NULL, 
    PSICOLOGO INTEGER NOT NULL, 
    EXAMEFISICO TEXT, 
    ANTIBIOTICO TEXT, 
    NUTRICAOORAL INTEGER NOT NULL, 
    NUTRICAOGT INTEGER NOT NULL, 
    NUTRICAOCNE INTEGER NOT NULL,
    NUTRICAOIV INTEGER NOT NULL, 
    ATIVIDADEVIDADIARIA INTEGER NOT NULL, 
    PAMAX INTEGER NOT NULL, 
    PAMIN INTEGER NOT NULL, 
    FC TEXT, 
    FR TEXT, 
    NIVELCONSCIENCIARM INTEGER, 
    NIVELCONSCIENCIARV INTEGER, 
    NIVELCONSCIENCIAAO INTEGER, 
    NIVELCONSCIENCIAPONTOS INTEGER, 
    VENTILACAOMECANICA INTEGER, 
    VENTILADOR TEXT, 
    OSTOMIATRAQUEOSTOMIA INTEGER NOT NULL, 
    OSTOMIAGASTROSTOMIA INTEGER NOT NULL, 
    OSTOMIACATETERNASOENTERAL INTEGER NOT NULL, 
    OSTOMIACISTOSTOMIA INTEGER NOT NULL, 
    OSTOMIACOLOSTOMIA INTEGER NOT NULL, 
    OSTOMIAOUTROS TEXT, 
    ASPIRACAOTRAQUEAL INTEGER, 
    ACESSOVENOSO INTEGER, 
    SUPORTEOXIGENIOCILINDRO INTEGER, 
    SUPORTEOXIGENIOCONCENTRADOR INTEGER, 
    OXIGENOTERAPIA INTEGER, 
    SOLICITAREXAME INTEGER, 
    MUDANCAPRESCRICAO INTEGER, 
    PROBLEMAS TEXT, 
    ORIENTACAO TEXT,
    ASSINATURAPACIENTE TEXT NOT NULL,
    ASSINATURAPROFISSIONAL TEXT NOT NULL,
    LATITUDE TEXT, 
    LONGITUDE TEXT,     
    NMPACIENTE INTEGER NOT NULL
  );
  ''';
}
