import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:srmobile/helpers/constantes.dart';

class CriaBanco {
  // Construtor com acesso privado
  CriaBanco._();

  // Criar uma instancia de CriaBanco
  static final CriaBanco instance = CriaBanco._();

  // Instancia do SQLite
  static Database? _database;

  get database async {
    if (_database != null) {
      return _database;
    } else {
      return await _initDatabase();
    }
  }

  _initDatabase() async {
    return await openDatabase(join(await getDatabasesPath(), BANCODB),
        version: 1, onCreate: _onCreate);
  }

  _onCreate(db, versao) async {
    await db.execute(_sqlFichaTerapia);
    await db.execute(_sqlFichaMedica);
    await db.execute(_sqlFichaEnfermagem);
    await db.execute(_sqlFichaNutricao);
    await db.execute(_sqlFichaTecnicoBase);
  }

  String get _sqlFichaTerapia => '''
  CREATE TABLE TB_FICHATERAPIA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    IDADMISSION INTEGER, 
    IDCAPCONSULT INTEGER, 
    IDPROFAGENDA INTEGER, 
    DATAINICIO TEXT, 
    DATAFIM TEXT, 
    ASSINATURAPACIENTE TEXT, 
    ASSINATURAPROFISSIONAL TEXT, 
    LATITUDE TEXT, 
    LONGITUDE TEXT, 
    IDPROFESSIONAL INTEGER, 
    NMPACIENTE TEXT
  );
  ''';

  String get _sqlFichaMedica => '''
  CREATE TABLE TB_FICHAMEDICA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IDADMISSION INTEGER NOT NULL, 
    IDCAPCONSULT INTEGER NOT NULL,
    IDPROFAGENDA INTEGER NOT NULL, 
    DATAINICIO TEXT NOT NULL, 
    DATAFIM TEXT NOT NULL, 
    IDPROFESSIONAL INTEGER NOT NULL, 
    HD TEXT NOT NULL, 
    ACOMPANHANTE TEXT NOT NULL, 
    SITUACAOCLINICA TEXT NOT NULL, 
    JUSTIFICATIVAATENDIMENTODOMICILIAR TEXT, 
    FISIOTERAPIAMOTORA INTEGER NOT NULL,
    FISIOTERAPIARESPIRATORIA INTEGER NOT NULL, 
    NUTRICIONISTA INTEGER NOT NULL, 
    FONOTERAPIA INTEGER NOT NULL, 
    ENFERMAGEM INTEGER NOT NULL, 
    TERAPIAOCUPACIONAL INTEGER NOT NULL, 
    PSICOLOGO INTEGER NOT NULL, 
    EXAMEFISICO TEXT, 
    ANTIBIOTICO TEXT, 
    NUTRICAOORAL INTEGER NOT NULL, 
    NUTRICAOGT INTEGER NOT NULL, 
    NUTRICAOCNE INTEGER NOT NULL,
    NUTRICAOIV INTEGER NOT NULL, 
    ATIVIDADEVIDADIARIA INTEGER NOT NULL, 
    PAMAX INTEGER NOT NULL, 
    PAMIN INTEGER NOT NULL, 
    FC TEXT, 
    FR TEXT, 
    NIVELCONSCIENCIARM INTEGER, 
    NIVELCONSCIENCIARV INTEGER, 
    NIVELCONSCIENCIAAO INTEGER, 
    NIVELCONSCIENCIAPONTOS INTEGER, 
    VENTILACAOMECANICA INTEGER, 
    VENTILADOR TEXT, 
    OSTOMIATRAQUEOSTOMIA INTEGER NOT NULL, 
    OSTOMIAGASTROSTOMIA INTEGER NOT NULL, 
    OSTOMIACATETERNASOENTERAL INTEGER NOT NULL, 
    OSTOMIACISTOSTOMIA INTEGER NOT NULL, 
    OSTOMIACOLOSTOMIA INTEGER NOT NULL, 
    OSTOMIAOUTROS TEXT, 
    ASPIRACAOTRAQUEAL INTEGER, 
    ACESSOVENOSO INTEGER, 
    SUPORTEOXIGENIOCILINDRO INTEGER, 
    SUPORTEOXIGENIOCONCENTRADOR INTEGER, 
    OXIGENOTERAPIA INTEGER, 
    SOLICITAREXAME INTEGER, 
    MUDANCAPRESCRICAO INTEGER, 
    PROBLEMAS TEXT, 
    ORIENTACAO TEXT,
    ASSINATURAPACIENTE TEXT NOT NULL,
    ASSINATURAPROFISSIONAL TEXT NOT NULL,
    LATITUDE TEXT, 
    LONGITUDE TEXT,     
    NMPACIENTE INTEGER NOT NULL
  );
  ''';

  // ignore: prefer_interpolation_to_compose_strings
  String get _sqlFichaEnfermagem => '''  CREATE TABLE $TB_FICHAENFERMAGEM(
    $TB_FICHAENFERMAGEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    $TB_FICHAENFERMAGEM_IDADMISSION INTEGER NOT NULL, 
    $TB_FICHAENFERMAGEM_IDCAPCONSULT INTEGER NOT NULL,
    $TB_FICHAENFERMAGEM_IDPROFAGENDA INTEGER NOT NULL, 
    $TB_FICHAENFERMAGEM_DATAINICIO TEXT NOT NULL, 
    $TB_FICHAENFERMAGEM_DATAFIM TEXT NOT NULL, 
    $TB_FICHAENFERMAGEM_IDPROFESSIONAL INTEGER NOT NULL, 
    $TB_FICHAENFERMAGEM_ACOMPANHANTE TEXT, 
    $TB_FICHAENFERMAGEM_HOSPITAL TEXT,
    $TB_FICHAENFERMAGEM_CUIDADOBANHO INTEGER,
    $TB_FICHAENFERMAGEM_CUIDADOVESTIR INTEGER, 
    $TB_FICHAENFERMAGEM_CUIDADOTRANSFERENCIA INTEGER, 
    $TB_FICHAENFERMAGEM_CUIDADOCONTINENCIA INTEGER, 
    $TB_FICHAENFERMAGEM_CUIDADOALIMENTACAO INTEGER, 
    $TB_FICHAENFERMAGEM_UTILIZACAOTQT INTEGER,
    $TB_FICHAENFERMAGEM_UTILIZACAOCNE INTEGER, 
    $TB_FICHAENFERMAGEM_UTILIZACAOGT INTEGER,
    $TB_FICHAENFERMAGEM_UTILIZACAOCVD INTEGER, 
    $TB_FICHAENFERMAGEM_UTILIZACAOOUTROS INTEGER,
    $TB_FICHAENFERMAGEM_UTILIZACAOOUTROSTEXTO TEXT, 
    $TB_FICHAENFERMAGEM_OXIGENOTERAPIACILINDRO INTEGER, 
    $TB_FICHAENFERMAGEM_OXIGENOTERAPIACONCENTRADOR INTEGER, 
    $TB_FICHAENFERMAGEM_OXIGENOTERAPIACONTINUO INTEGER, 
    $TB_FICHAENFERMAGEM_OXIGENOTERAPIANAO INTEGER, 
    $TB_FICHAENFERMAGEM_VENTILACAOMECANICA INTEGER, 
    $TB_FICHAENFERMAGEM_VENTILACAOMECANICAEQUIPAMENTO TEXT, 
    $TB_FICHAENFERMAGEM_PAMAX INTEGER, 
    $TB_FICHAENFERMAGEM_PAMIN INTEGER, 
    $TB_FICHAENFERMAGEM_FERIDAPRESSAO INTEGER,
    $TB_FICHAENFERMAGEM_FERIDAVASCULOGENCIA INTEGER,
    $TB_FICHAENFERMAGEM_FERIDACIRURGIA INTEGER, 
    $TB_FICHAENFERMAGEM_FERIDAOUTROS TEXT, 
    $TB_FICHAENFERMAGEM_DIAG001 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG002 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG003 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG004 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG005 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG006 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG007 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG008 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG009 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG010 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG011 INTEGER, 
    $TB_FICHAENFERMAGEM_DIAG012 INTEGER,  
    $TB_FICHAENFERMAGEM_DIAG013 INTEGER,  
    $TB_FICHAENFERMAGEM_DIAG014 INTEGER,  
    $TB_FICHAENFERMAGEM_DIAG015 INTEGER,
    $TB_FICHAENFERMAGEM_PROC001 INTEGER,
    $TB_FICHAENFERMAGEM_PROC002 INTEGER,
    $TB_FICHAENFERMAGEM_PROC003 INTEGER,
    $TB_FICHAENFERMAGEM_PROC004 INTEGER,
    $TB_FICHAENFERMAGEM_PROC005 INTEGER,
    $TB_FICHAENFERMAGEM_PROC006 INTEGER,
    $TB_FICHAENFERMAGEM_PROC007 INTEGER,
    $TB_FICHAENFERMAGEM_PROC008 INTEGER, 
    $TB_FICHAENFERMAGEM_PROCOUTROS INTEGER, 
    $TB_FICHAENFERMAGEM_PROCOUTROSTEXTO TEXT,
    $TB_FICHAENFERMAGEM_CUID001 INTEGER,
    $TB_FICHAENFERMAGEM_CUID002 INTEGER,
    $TB_FICHAENFERMAGEM_CUID003 INTEGER,
    $TB_FICHAENFERMAGEM_CUID004 INTEGER,
    $TB_FICHAENFERMAGEM_CUID005 INTEGER,
    $TB_FICHAENFERMAGEM_CUID006 INTEGER,
    $TB_FICHAENFERMAGEM_CUID007 INTEGER,
    $TB_FICHAENFERMAGEM_CUID008 INTEGER,
    $TB_FICHAENFERMAGEM_CUIDOUTROS INTEGER,
    $TB_FICHAENFERMAGEM_CUIDOUTROSTEXTO TEXT, 
    $TB_FICHAENFERMAGEM_BRADENPERCEPCAOSENSORIAL INTEGER,
    $TB_FICHAENFERMAGEM_BRADENUMIDADE INTEGER, 
    $TB_FICHAENFERMAGEM_BRADENATIVIDADE INTEGER, 
    $TB_FICHAENFERMAGEM_BRADENMOBILIDADE INTEGER, 
    $TB_FICHAENFERMAGEM_BRADENNUTRICAO INTEGER,
    $TB_FICHAENFERMAGEM_BRADENFICCAO INTEGER, 
    $TB_FICHAENFERMAGEM_OBSERVACAO TEXT, 
    $TB_FICHAENFERMAGEM_ASSINATURAPACIENTE TEXT NOT NULL,
    $TB_FICHAENFERMAGEM_ASSINATURAPROFISSIONAL TEXT NOT NULL,
    $TB_FICHAENFERMAGEM_LATITUDE TEXT, 
    $TB_FICHAENFERMAGEM_LONGITUDE TEXT,     
    $TB_FICHAENFERMAGEM_NMPACIENTE INTEGER NOT NULL
  );
  ''';

  String get _sqlFichaNutricao => '''  CREATE TABLE $TB_FICHANUTRICAO(
    $TB_FICHANUTRICAO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    $TB_FICHANUTRICAO_IDADMISSION INTEGER NOT NULL, 
    $TB_FICHANUTRICAO_IDCAPCONSULT INTEGER NOT NULL,
    $TB_FICHANUTRICAO_IDPROFAGENDA INTEGER NOT NULL, 
    $TB_FICHANUTRICAO_DATAINICIO TEXT NOT NULL, 
    $TB_FICHANUTRICAO_DATAFIM TEXT NOT NULL, 
    $TB_FICHANUTRICAO_IDPROFESSIONAL INTEGER NOT NULL, 
    $TB_FICHANUTRICAO_ACOMPANHANTE TEXT, 
    $TB_FICHANUTRICAO_GRUPOHAS TEXT,
    $TB_FICHANUTRICAO_GRUPODIABETES TEXT,
    $TB_FICHANUTRICAO_GRUPODISLIPIDEMIA TEXT,
    $TB_FICHANUTRICAO_GRUPOIMOBILIDADE TEXT,
    $TB_FICHANUTRICAO_GRUPOOBESIDADE TEXT,
    $TB_FICHANUTRICAO_GRUPODESNUTRICAO TEXT,
    $TB_FICHANUTRICAO_GRUPOOUTROS TEXT,
    $TB_FICHANUTRICAO_NUTRICAO INTEGER,
    $TB_FICHANUTRICAO_NUTRICAOTIPOENTERAL INTEGER, 
    $TB_FICHANUTRICAO_NUTRICAOOUTROS TEXT, 
    $TB_FICHANUTRICAO_DIETAENTERAL INTEGER, 
    $TB_FICHANUTRICAO_DIETAENTERALENTUPIMENTO TEXT, 
    $TB_FICHANUTRICAO_DIETAINDUSTIPO INTEGER,
    $TB_FICHANUTRICAO_DIETAINDUSMANIPQTDE TEXT, 
    $TB_FICHANUTRICAO_DIETAINDUSMANIPDESC TEXT,
    $TB_FICHANUTRICAO_DIETAINDUSPRONTAQTDE TEXT,
    $TB_FICHANUTRICAO_DIETAINDUSPRONTADESC TEXT,
    $TB_FICHANUTRICAO_DIETAINDUSPRONTAFAB TEXT,
    $TB_FICHANUTRICAO_DIETAINDUSFORNECEDOR INTEGER,
    $TB_FICHANUTRICAO_AVALSUBJINGESTA INTEGER,
    $TB_FICHANUTRICAO_AVALSUBJPESOTIPO INTEGER,
    $TB_FICHANUTRICAO_AVALSUBJPESOQTDE TEXT,
    $TB_FICHANUTRICAO_AVALSUBJPESOTEMPO TEXT,
    $TB_FICHANUTRICAO_AVALSUBJSINTOMADIARREIA TEXT,
    $TB_FICHANUTRICAO_AVALSUBJSINTOMAHIPOREXIA TEXT,
    $TB_FICHANUTRICAO_AVALSUBJSINTOMACONSTIPACAO TEXT,
    $TB_FICHANUTRICAO_AVALSUBJSINTOMAOUTROS TEXT,
    $TB_FICHANUTRICAO_AVALSUBJRITMOINTESTINAL TEXT,
    $TB_FICHANUTRICAO_AVALANTROAJ TEXT,
    $TB_FICHANUTRICAO_AVALANTROPESO TEXT,
    $TB_FICHANUTRICAO_AVALANTROCIRCABD TEXT,
    $TB_FICHANUTRICAO_AVALANTROIMC TEXT,
    $TB_FICHANUTRICAO_AVALANTROCP TEXT,
    $TB_FICHANUTRICAO_AVALANTROIDADE TEXT,
    $TB_FICHANUTRICAO_AVALANTRODCT TEXT,
    $TB_FICHANUTRICAO_AVALANTROCB TEXT,
    $TB_FICHANUTRICAO_AVALANTROCMB TEXT,
    $TB_FICHANUTRICAO_AVALANTROALTURA TEXT,
    $TB_FICHANUTRICAO_DIAGNUTRIABAIXO65 INTEGER,
    $TB_FICHANUTRICAO_DIAGNUTRIACIMA65 INTEGER,
    $TB_FICHANUTRICAO_DIAGNUTRIDESC TEXT,
    $TB_FICHANUTRICAO_MANTERCONDUTA TEXT,
    $TB_FICHANUTRICAO_CONDUTA TEXT,
    $TB_FICHANUTRICAO_ASSINATURAPACIENTE TEXT NOT NULL,
    $TB_FICHANUTRICAO_ASSINATURAPROFISSIONAL TEXT NOT NULL,
    $TB_FICHANUTRICAO_LATITUDE TEXT, 
    $TB_FICHANUTRICAO_LONGITUDE TEXT,     
    $TB_FICHANUTRICAO_NMPACIENTE INTEGER NOT NULL
  );
  ''';

  String get _sqlFichaTecnicoBase => '''  CREATE TABLE $TB_FICHATECNICOBASE(
    $TB_FICHATECNICOBASE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    $TB_FICHATECNICOBASE_IDADMISSION INTEGER NOT NULL, 
    $TB_FICHATECNICOBASE_IDCAPCONSULT INTEGER NOT NULL,
    $TB_FICHATECNICOBASE_IDPROFAGENDA INTEGER NOT NULL, 
    $TB_FICHATECNICOBASE_DATAINICIO TEXT NOT NULL, 
    $TB_FICHATECNICOBASE_DATAFIM TEXT NOT NULL, 
    $TB_FICHATECNICOBASE_IDPROFESSIONAL INTEGER NOT NULL, 
    $TB_FICHATECNICOBASE_TIPOCHAMADA INTEGER, 
    $TB_FICHATECNICOBASE_PROC001 INTEGER,
    $TB_FICHATECNICOBASE_PROC002 INTEGER,
    $TB_FICHATECNICOBASE_PROC003 INTEGER,
    $TB_FICHATECNICOBASE_PROC004 INTEGER,
    $TB_FICHATECNICOBASE_PROC005 INTEGER,
    $TB_FICHATECNICOBASE_PROC006 INTEGER,
    $TB_FICHATECNICOBASE_PROC007 INTEGER,
    $TB_FICHATECNICOBASE_PROC008 INTEGER,
    $TB_FICHATECNICOBASE_PROC009 INTEGER,
    $TB_FICHATECNICOBASE_PROC010 INTEGER,
    $TB_FICHATECNICOBASE_PROC011 INTEGER,
    $TB_FICHATECNICOBASE_PROC012 INTEGER,
    $TB_FICHATECNICOBASE_PROC_OUTROS TEXT,
    $TB_FICHATECNICOBASE_ABD TEXT,
    $TB_FICHATECNICOBASE_ALGODAO TEXT,
    $TB_FICHATECNICOBASE_AGULHA TEXT,
    $TB_FICHATECNICOBASE_ALCOOL TEXT,
    $TB_FICHATECNICOBASE_ATADURA TEXT,
    $TB_FICHATECNICOBASE_CATETER TEXT,
    $TB_FICHATECNICOBASE_EQUIPO TEXT, 
    $TB_FICHATECNICOBASE_EXTENSOR1VIA TEXT, 
    $TB_FICHATECNICOBASE_EXTENSOR2VIA TEXT, 
    $TB_FICHATECNICOBASE_GAZEACOLCHOADA TEXT, 
    $TB_FICHATECNICOBASE_GAZEEMBEBIDA TEXT,
    $TB_FICHATECNICOBASE_GAZEESTERIL TEXT, 
    $TB_FICHATECNICOBASE_HEPARINA TEXT,
    $TB_FICHATECNICOBASE_IVFIX TEXT,
    $TB_FICHATECNICOBASE_JELCO TEXT,
    $TB_FICHATECNICOBASE_BISTURI TEXT,
    $TB_FICHATECNICOBASE_LUVAESTERIL TEXT,
    $TB_FICHATECNICOBASE_LUVAPROCEDIMENTO TEXT,
    $TB_FICHATECNICOBASE_MASCARA TEXT,
    $TB_FICHATECNICOBASE_MICROPORE2510 TEXT,
    $TB_FICHATECNICOBASE_MICROPORE5010 TEXT,
    $TB_FICHATECNICOBASE_SCALP TEXT,
    $TB_FICHATECNICOBASE_SERINGA TEXT,
    $TB_FICHATECNICOBASE_SOROFISIOLOGICO TEXT,
    $TB_FICHATECNICOBASE_OUTROSMATERIAIS TEXT,
    $TB_FICHATECNICOBASE_MEDICAMENTOS TEXT,
    $TB_FICHATECNICOBASE_EVOLUCAO TEXT,
    $TB_FICHATECNICOBASE_ASSINATURAPACIENTE TEXT NOT NULL,
    $TB_FICHATECNICOBASE_ASSINATURAPROFISSIONAL TEXT NOT NULL,
    $TB_FICHATECNICOBASE_LATITUDE TEXT, 
    $TB_FICHATECNICOBASE_LONGITUDE TEXT,     
    $TB_FICHATECNICOBASE_NMPACIENTE INTEGER NOT NULL
  );
  ''';
}
